name: Brennen Barrigar
favicon: null
layout_spectrum: 0.7359391583595425
typography_spectrum: 0.15466788527555764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2940867014694959
  lightness: 0.07732446282170713
  saturation: 0.3945499586407095
  rhythmicContrast: 0.6228877592366189
purpose: []
