name: Brennen Barrigar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.751
title: Brennen Barrigar Yeah
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#82b1c3'
    - '#fbffff'
    - '#527092'
    - '#cd2815'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
